Repository NycoChavanoud/atempo, pull requests merged in 2022-07, with the labels that each got.

#41 validation for the clients modifications ok
  components/ClientCard/ClientCard.module.css
  components/ClientCardList/ClientCardList.module.css
  components/ClientDetails/ClientDetails.module.css
  components/ClientEditSteps/ClientsEditSteps.js
  components/ClientForm/ClientForm.js
  components/ClientForm/ClientForm.module.css
  components/ClientForm/MotifForm.js
  components/ClientsSteps/ClientsSteps.js
  components/ClientsSteps/ClientsSteps.module.css
  components/DesktopMenu/DesktopMenu.js
  components/DesktopMenu/DesktopMenu.module.css
  components/GreyBurger/GreyBurger.module.css
  components/SeanceDetails/SeanceDetails.module.css
  components/Wave/Wave.module.css
  components/WaveWhiteBurger/WaveWhiteBurger.module.css
  components/WhiteBurger/WhiteBurger.module.css
  components/WhiteCross/WhiteCross.module.css
  package-lock.json
  pages/clients/[id]/clientDetails.module.css
  pages/clients/[id]/edit.js
  pages/clients/[id]/index.js
  pages/clients/clients.module.css
  pages/clients/creationClient.module.css
  pages/clients/index.js
  pages/dashboard/dashboard.module.css
  pages/dashboard/index.js
  pages/index.js
  pages/profile/index.js
  pages/profile/profile.module.css
  pages/seances/index.js
  styles/Seances.module.css
  yarn.lock
Labels: Ready for prod

#37 Photo
  components/Account/Account.module.css
  components/Avatar/Avatar.js
  components/Avatar/avatar.module.css
  components/Deconnexion/Deconnexion.js
  components/Deconnexion/deconnexion.module.css
  components/DesktopMenu/DesktopMenu.js
  components/DisplayCurrentUser/DisplayCurrentUser.js
  components/DisplayCurrentUser/DisplayCurrentUser.module.css
  components/Layout/Layout.module.css
  components/WaveAdmin/WaveAdmin.js
  context/authContext.js
  model/PractitionersData/practitionersData.js
  package-lock.json
  package.json
  pages/clients/[id]/edit.js
  pages/clients/creationClient.js
  pages/clients/index.js
  pages/dashboard/dashboard.module.css
  pages/dashboard/index.js
  pages/index.js
  pages/inscription/index.js
  pages/inscription/inscription.module.css
  pages/menu/index.js
  pages/profile/editPractitioner.js
  pages/profile/index.js
  pages/profile/modif-profile.module.css
  pages/profile/profile.module.css
  pages/resetpwd/index.js
  pages/resetpwd/passwordReset.module.css
  pages/seances/index.js
  public/images/arrow2.png
  public/images/bg_shape_white.png
  public/images/fb.png
  public/images/headerAdmin.png
  public/images/insta.png
  public/images/left-arrow2.png
  public/images/pen.png
  public/img/retour.png
  public/img/tete-profil.png
  public/img/twitter.png
  public/img/whatsapp.png
  styles/connexion.module.css
  yarn.lock
Labels: Ready for prod

#39 add pagination on seance
  components/Layout/Layout.module.css
  components/ProgressStepper/ProgressStepper.js
  components/Recorder/Recorder.js
  components/SeanceCard/Duration.js
  components/SeanceCard/SeanceCard.js
  components/SeanceCard/SeanceCard.module.css
  components/SeanceCardList/SeanceCardList.js
  components/SeanceCardList/SeanceCardList.module.css
  components/SeanceDetails/SeanceDetails.js
  components/SeanceForm/AddClientsForm.js
  components/SeanceForm/DescriptionForm.js
  components/SeanceForm/MainDataForm.js
  components/SeanceForm/UploadMediaForm.js
  context/createSeanceContext.js
  model/seances.js
  package-lock.json
  package.json
  pages/inscription/index.js
  pages/seances/[id]/edit.js
  pages/seances/[id]/index.js
  pages/seances/create.js
  pages/seances/index.js
  styles/Seances.module.css
  styles/globals.css
  yarn.lock
Labels: Ready for prod

#44 Client pag
  components/Account/Account.module.css
  components/ClientCard/ClientCard.js
  components/ClientCardList/ClientCardList.js
  components/ClientCardList/ClientCardList.module.css
  components/ClientEditSteps/ClientsEditSteps.js
  components/ClientForm/ClientForm.module.css
  components/ClientsSteps/ClientsSteps.js
  components/DesktopMenu/DesktopMenu.js
  components/DesktopMenu/DesktopMenu.module.css
  model/client.js
  package-lock.json
  package.json
  pages/clients/[id]/clientDetails.module.css
  pages/clients/[id]/edit.js
  pages/clients/[id]/index.js
  pages/clients/clients.module.css
  pages/clients/creationClient.js
  pages/clients/creationClient.module.css
  pages/clients/index.js
  pages/dashboard/dashboard.module.css
  pages/profile/profile.module.css
  styles/Seances.module.css
  yarn.lock
Labels: Ready for validation

#45 Linkseances
  components/AssociatedClients/AssociatedClients.js
  components/ClientCard/ClientCard.js
  components/ClientCard/ClientCard.module.css
  components/ClientCardList/ClientCardList.js
  components/LinkedClientModal/LinkedClientModal.js
  components/LinkedClientModal/LinkedClientModal.module.css
  components/LinkedClientModal/LinkedClientModalUpdate.js
  components/ProgressStepper/ProgressStepper.js
  components/SeanceCard/SeanceCard.js
  components/SeanceCard/SeanceCard.module.css
  components/SeanceCardList/SeanceCardList.js
  components/SeanceCardList/SeanceCardList.module.css
  components/SeanceDetails/SeanceDetails.js
  components/SeanceForm/AddClientsForm.js
  components/SeanceForm/Summary.js
  components/SeanceForm/UploadMediaForm.js
  model/client.js
  model/seances.js
  package-lock.json
  pages/clients/[id]/clientDetails.module.css
  pages/clients/[id]/index.js
  pages/seances/[id]/index.js
  pages/seances/index.js
  yarn.lock
Labels: Ready for prod

#48 Fixlastbug
  components/Deconnexion/Deconnexion.js
  components/DesktopMenu/DesktopMenu.js
  components/DisplayCurrentUser/DisplayCurrentUser.module.css
  components/SeanceCardList/SeanceCardList.js
  components/SeanceCardList/SeanceCardList.module.css
  context/authContext.js
  model/client.js
  pages/profile/editPractitioner.js
Labels: Ready for prod

#51 Chris debug
  .env.example
  components/ClientCardList/ClientCardList.js
  components/ClientCardList/ClientCardList.module.css
  components/ClientDetails/ClientDetails.js
  components/ClientDetails/ClientDetails.module.css
  components/ClientForm/ClientForm.js
  components/ClientForm/ClientForm.module.css
  components/ClientForm/MotifForm.js
  components/ClientsSteps/ClientsSteps.js
  components/ClientsSteps/ClientsSteps.module.css
  components/Deconnexion/deconnexion.module.css
  components/DesktopMenu/DesktopMenu.module.css
  components/DisplayCurrentUser/DisplayCurrentUser.module.css
  model/client.js
  package-lock.json
  pages/clients/[id]/clientDetails.module.css
  pages/clients/[id]/index.js
  pages/clients/clients.module.css
  pages/clients/creationClient.js
  pages/clients/creationClient.module.css
  pages/seances/[id]/index.js
  yarn.lock
Labels: Ready for validation

#52 Dev
  .env.example
  components/AssociatedClients/AssociatedClients.js
  components/ClientCardList/ClientCardList.js
  components/ClientCardList/ClientCardList.module.css
  components/ClientDetails/ClientDetails.js
  components/ClientDetails/ClientDetails.module.css
  components/ClientForm/ClientForm.js
  components/ClientForm/ClientForm.module.css
  components/ClientForm/MotifForm.js
  components/ClientsSteps/ClientsSteps.js
  components/ClientsSteps/ClientsSteps.module.css
  components/Deconnexion/Deconnexion.js
  components/Deconnexion/deconnexion.module.css
  components/DesktopMenu/DesktopMenu.js
  components/DesktopMenu/DesktopMenu.module.css
  components/DisplayCurrentUser/DisplayCurrentUser.js
  components/DisplayCurrentUser/DisplayCurrentUser.module.css
  components/LinkedClientModal/LinkedClientModal.js
  components/LinkedClientModal/LinkedClientModalUpdate.js
  components/ProgressStepper/ProgressStepper.js
  components/SeanceCard/Duration.js
  components/SeanceCard/SeanceCard.js
  components/SeanceCardList/SeanceCardList.js
  components/SeanceCardList/SeanceCardList.module.css
  components/SeanceDetails/SeanceDetails.js
  components/SeanceForm/AddClientsForm.js
  components/SeanceForm/DescriptionForm.js
  components/SeanceForm/MainDataForm.js
  components/SeanceForm/RecordForm.js
  components/SeanceForm/SeanceForm.module.css
  components/SeanceForm/Summary.js
  components/SeanceForm/UploadMediaForm.js
  context/authContext.js
  model/client.js
  model/seances.js
  package-lock.json
  pages/clients/[id]/clientDetails.module.css
  pages/clients/[id]/index.js
  pages/clients/clients.module.css
  pages/clients/creationClient.js
  pages/clients/creationClient.module.css
  pages/index.js
  pages/inscription/index.js
  pages/profile/editPractitioner.js
  pages/seances/[id]/edit.js
  pages/seances/[id]/index.js
  pages/seances/createFromMenu.js
  styles/Seances.module.css
  yarn.lock
Labels: Ready for prod

#46 Modifprofile
  components/SeanceCardList/SeanceCardList.js
  components/Stats-clients.js
  components/Stats-seance.js
  model/dashboardData.js
  package-lock.json
  pages/dashboard/dashboard.module.css
  pages/dashboard/index.js
  pages/profile/editPractitioner.js
  pages/profile/index.js
  pages/profile/modif-profile.module.css
  pages/profile/profile.module.css
  public/img/retour.png
Labels: WIP
