Repository NycoChavanoud/atempo, pull requests merged in 2022-06, with the labels that each got.

#26 Profile1
  components/stats-clients.js
  components/stats-seance.js
  cypress/integration/dashboard.spec.js
  package-lock.json
  package.json
  pages/dashboard/dashboard.module.css
  pages/dashboard/edit.js
  pages/dashboard/index.js
  pages/profile/edit.js
  pages/profile/index.js
  pages/profile/profile.module.css
  public/img/fb.png
  public/img/insta.png
  public/img/pen.png
  public/img/tete-profil.png
  public/img/wave.png
Labels: Ready for validation

#29 Connexion
  .gitignore
  components/Account/Account.js
  components/Account/Account.module.css
  components/ProtectedRoute/protectedRoute.js
  config/firebaseConfig.js
  context/authContext.js
  cypress/plugins/index.js
  cypress/support/commands.js
  package-lock.json
  package.json
  pages/index.js
  pages/inscription/index.js
  pages/inscription/inscription.module.css
  pages/menu/index.js
  pages/resetpwd/index.js
  pages/resetpwd/passwordReset.module.css
  styles/connexion.module.css
Labels: Ready for validation

#24 create pages (sessions, sessions/id, sessions/create), create compone…
  .env.example
  components/AssociatedClients/AssociatedClients.js
  components/AssociatedClients/AssociatedClients.module.css
  components/BurgerButton/BurgerButton.js
  components/BurgerButton/BurgerButton.module.css
  components/GreyBurger/GreyBurger.js
  components/GreyBurger/GreyBurger.module.css
  components/Layout/Layout.js
  components/Layout/Layout.module.css
  components/ProgressStepper/ProgressStepper.js
  components/SeanceCard/SeanceCard.js
  components/SeanceCard/SeanceCard.module.css
  components/SeanceCardList/SeanceCardList.js
  components/SeanceCardList/SeanceCardList.module.css
  components/SeanceDetails/SeanceDetails.js
  components/SeanceDetails/SeanceDetails.module.css
  components/SeanceForm/AddClientsForm.js
  components/SeanceForm/DescriptionForm.js
  components/SeanceForm/MainDataForm.js
  components/SeanceForm/RecordForm.js
  components/SeanceForm/SeanceForm.module.css
  components/SeanceForm/Summary.js
  components/SeanceForm/UploadMediaForm.js
  config/firebaseConfig.js
  context/createSeanceContext.js
  model/Clients/CreateClient.js
  model/resetFireBaseDB.js
  model/seances.js
  package-lock.json
  package.json
  pages/resetpwd/index.js
  pages/seances/[id]/edit.js
  pages/seances/[id]/index.js
  pages/seances/create.js
  pages/seances/index.js
  postcss.config.js
  public/bg_shape_white.png
  public/bg_wave.png
  public/favicon.ico
  public/wave.svg
  styles/Seances.module.css
  styles/globals.css
  tailwind.config.js
Labels: Ready for prod, Ready for validation

#32 Connexion
  components/Account/Account.js
  components/Layout/Layout.js
  components/ProtectedRoute/protectedRoute.js
  context/authContext.js
  package.json
  pages/_app.js
  pages/index.js
  pages/resetpwd/index.js
  public/images/google-logo.png
  public/images/padlock.png
  styles/connexion.module.css
  yarn.lock
Labels: Ready for prod

#35 Modification Seances
  components/ProgressStepper/ProgressStepper.js
  components/SeanceCardList/SeanceCardList.js
  components/SeanceCardList/SeanceCardList.module.css
  components/SeanceDetails/SeanceDetails.js
  components/SeanceForm/DescriptionForm.js
  components/SeanceForm/MainDataForm.js
  components/SeanceForm/SeanceForm.module.css
  components/SeanceForm/Summary.js
  components/SeanceForm/UploadMediaForm.js
  context/createSeanceContext.js
  model/resetFireBaseDB.js
  model/seances.js
  pages/seances/[id]/edit.js
  pages/seances/[id]/index.js
  pages/seances/index.js
  styles/Seances.module.css
Labels: Ready for prod
